'use server'

import { createClient } from '@/utils/supabase/server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'

// ▼ LINE設定の保存（変更なしだが、念のため記載）
export async function saveLineSettings(formData: FormData) {
  const token = formData.get('token') as string
  const secret = formData.get('secret') as string

  if (!token || !secret) return { error: 'すべての項目を入力してください' }

  // 疎通確認
  const lineRes = await fetch('https://api.line.me/v2/bot/info', {
    method: 'GET',
    headers: { Authorization: `Bearer ${token}` },
  })

  if (!lineRes.ok) return { error: '認証に失敗しました。' }

  const lineData = await lineRes.json()
  const botUserId = lineData.userId
  const basicId = lineData.basicId 
  const autoGeneratedUrl = `https://line.me/R/ti/p/${basicId}`

  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) return { error: 'ログインが必要です' }

  // line_settings 保存
  const { error: dbError } = await supabase
    .from('line_settings')
    .upsert({
      user_id: user.id,
      channel_access_token: token,
      channel_secret: secret,
      bot_user_id: botUserId,
    }, { onConflict: 'user_id' })

  if (dbError) return { error: 'LINE設定の保存に失敗しました' }

  // profiles の LINE URL も自動更新
  // (company_name等は触らず、line_urlだけ更新または新規作成)
  const { error: profileError } = await supabase
    .from('profiles')
    .upsert({ 
        id: user.id, 
        line_url: autoGeneratedUrl,
        updated_at: new Date().toISOString()
    }, { onConflict: 'id' }) // 既存の行があればマージされる（他カラムは消えない）

  revalidatePath('/dashboard/settings')
  redirect('/dashboard/settings')
}

// ▼ 会社情報の保存（★修正: URL入力を削除し、確実に保存する）
export async function updateProfile(formData: FormData) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  
  if (!user) return { error: 'ログインが必要です' }

  const companyName = formData.get('companyName') as string
  const phone = formData.get('phone') as string

  // upsertを使って保存（line_urlは含めない＝既存の値を維持する）
  const { error } = await supabase
    .from('profiles')
    .upsert({
      id: user.id,
      company_name: companyName,
      phone_number: phone,
      updated_at: new Date().toISOString(),
    }, { onConflict: 'id' })

  if (error) {
    console.error(error)
    return { error: '保存に失敗しました' }
  }

  // キャッシュ更新
  revalidatePath('/dashboard/settings')
  
  // 成功シグナル
  return { error: null }
}